name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test (go ${{ matrix.go_version }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        go_version: [1.16, 1.17]
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6
    - uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 #v2
    - run: make test